### ISSUE TITLE
GitHub button is invisible

### ISSUE THREAD

**Issue by Thunder8110** [ecto0310/atcoder_shojin_point#10]
![image](https://github.com/ecto0310/atcoder_shojin_point/assets/44309219/74154433-cbc1-4c8f-8ea8-1f86ae4a9111)

GitHubボタンが見えません（クリックはできます）
ブラウザ: Google Chrome
バージョン: 121.0.6167.140

**Comment by ecto0310** [comment]
ダークモードで開発してたのでライトモード考慮忘れてました!!
MUIのprimaryの色都合でこうなるみたいなのでcontainedにして白抜きにしました
